services:
  - name: virta7-ayaan-backend
    type: web
    runtime: node
    rootDir: virta7-server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_CODE
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
